### ISSUE TITLE
[Error] => No chrome installations found

### ISSUE THREAD

**Issue by AmityTek** [octoper/lighthouse-php#6]
Hi,

Screen : http://prntscr.com/w76fw4
Anyone can help me with this issue ?
I already set chrome_path in env windows ..

**node version : 14.4.0
os : windows 10
php : 8.0.0
lighthouse-cli : 7.0.0**

Thanks

**Comment by octoper** [comment]
Are you running it inside  WSL?

**Comment by AmityTek** [comment]
No, i'm using Laravel last version !

**Comment by octoper** [comment]
Oh I mean if you use Windows Subsystem for Linux for your development

**Comment by AmityTek** [comment]
No, I only use Windows 10 + VS code + wamp

**Comment by octoper** [comment]
I don't have windows right now to check it, please can you check if https://github.com/GoogleChrome/lighthouse works on Windows.
```
npm install -g lighthouse
lighthouse https://google.com --view
```

**Comment by octoper** [comment]
It's been lot of days without response so I'm going to close this issue and consider it resolved. If you have any questions or you think this issue is not resolved feel free to re-open it!
